// Code generated by cmd/gen; DO NOT EDIT.

package intervalsicu

import (
	"context"
	"fmt"
	"net/url"
)

type ApplyCurrentPlanChangesParams struct {
	ID string
}

type ApplyCurrentPlanChangesResult = ApplyCurrentPlanChangesResultBody

func (c *Client) ApplyCurrentPlanChanges(ctx context.Context, params ApplyCurrentPlanChangesParams) (*ApplyCurrentPlanChangesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ApplyCurrentPlanChangesResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/apply-plan-changes", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ApplyPlanParams struct {
	ID   string
	Body ApplyPlanDTO
}

type ApplyPlanResult = ApplyPlanResultBody

func (c *Client) ApplyPlan(ctx context.Context, params ApplyPlanParams) (*ApplyPlanResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ApplyPlanResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/events/apply-plan", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ApplyToActivitiesParams struct {
	AthleteID string
	ID        string
}

type ApplyToActivitiesResult = ApplyToActivitiesResultBody

func (c *Client) ApplyToActivities(ctx context.Context, params ApplyToActivitiesParams) (*ApplyToActivitiesResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out ApplyToActivitiesResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{athleteId}/sport-settings/{id}/apply", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CalcDistanceEtcParams struct {
	GearID string
	ID     string
}

type CalcDistanceEtcResult = GearStats

func (c *Client) CalcDistanceEtc(ctx context.Context, params CalcDistanceEtcParams) (*CalcDistanceEtcResult, error) {
	pathParams := map[string]string{
		"gearId": fmt.Sprint(params.GearID),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CalcDistanceEtcResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/gear/{gearId}/calc", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CheckMergeParams struct {
	ID      string
	OtherID int64
	RouteID int64
}

type CheckMergeResult = RouteSimilarity

func (c *Client) CheckMerge(ctx context.Context, params CheckMergeParams) (*CheckMergeResult, error) {
	pathParams := map[string]string{
		"id":       c.athleteIDOr(params.ID),
		"other_id": fmt.Sprint(params.OtherID),
		"route_id": fmt.Sprint(params.RouteID),
	}
	query := url.Values{}
	var out CheckMergeResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/routes/{route_id}/similarity/{other_id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateCustomItemParams struct {
	ID   string
	Body CustomItem
}

type CreateCustomItemResult = NewCustomItem

func (c *Client) CreateCustomItem(ctx context.Context, params CreateCustomItemParams) (*CreateCustomItemResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateCustomItemResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/custom-item", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateEventParams struct {
	ID          string
	UpsertOnUid bool
	Body        EventEx
}

type CreateEventResult = Event

func (c *Client) CreateEvent(ctx context.Context, params CreateEventParams) (*CreateEventResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("upsertOnUid", fmt.Sprint(params.UpsertOnUid))
	var out CreateEventResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/events", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateFolderParams struct {
	ID   string
	Body CreateFolderDTO
}

type CreateFolderResult = Folder

func (c *Client) CreateFolder(ctx context.Context, params CreateFolderParams) (*CreateFolderResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateFolderResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/folders", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateGearParams struct {
	ID   string
	Body Gear
}

type CreateGearResult = Gear

func (c *Client) CreateGear(ctx context.Context, params CreateGearParams) (*CreateGearResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateGearResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/gear", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateManualActivityParams struct {
	ID   string
	Body Activity
}

type CreateManualActivityResult = Activity

func (c *Client) CreateManualActivity(ctx context.Context, params CreateManualActivityParams) (*CreateManualActivityResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateManualActivityResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/activities/manual", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateMultipleEventsParams struct {
	ID                string
	UpdatePlanApplied bool
	Upsert            *bool
	UpsertOnUid       bool
	Body              CreateMultipleEventsRequestBody
}

type CreateMultipleEventsResult = CreateMultipleEventsResultBody

func (c *Client) CreateMultipleEvents(ctx context.Context, params CreateMultipleEventsParams) (*CreateMultipleEventsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("updatePlanApplied", fmt.Sprint(params.UpdatePlanApplied))
	if params.Upsert != nil {
		query.Set("upsert", fmt.Sprint(*params.Upsert))
	}
	query.Set("upsertOnUid", fmt.Sprint(params.UpsertOnUid))
	var out CreateMultipleEventsResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/events/bulk", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateMultipleManualActivitiesParams struct {
	ID   string
	Body CreateMultipleManualActivitiesRequestBody
}

type CreateMultipleManualActivitiesResult = CreateMultipleManualActivitiesResultBody

func (c *Client) CreateMultipleManualActivities(ctx context.Context, params CreateMultipleManualActivitiesParams) (*CreateMultipleManualActivitiesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateMultipleManualActivitiesResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/activities/manual/bulk", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateMultipleWorkoutsParams struct {
	ID   string
	Body CreateMultipleWorkoutsRequestBody
}

type CreateMultipleWorkoutsResult = CreateMultipleWorkoutsResultBody

func (c *Client) CreateMultipleWorkouts(ctx context.Context, params CreateMultipleWorkoutsParams) (*CreateMultipleWorkoutsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateMultipleWorkoutsResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/workouts/bulk", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateReminderParams struct {
	GearID string
	ID     string
	Body   GearReminder
}

type CreateReminderResult = Gear

func (c *Client) CreateReminder(ctx context.Context, params CreateReminderParams) (*CreateReminderResult, error) {
	pathParams := map[string]string{
		"gearId": fmt.Sprint(params.GearID),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateReminderResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/gear/{gearId}/reminder", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateSettingsParams struct {
	AthleteID string
	Body      SportSettings
}

type CreateSettingsResult = SportSettings

func (c *Client) CreateSettings(ctx context.Context, params CreateSettingsParams) (*CreateSettingsResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
	}
	query := url.Values{}
	var out CreateSettingsResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{athleteId}/sport-settings", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateSharedEventParams struct {
	LinkToEventID *int32
	Body          SharedEvent
}

type CreateSharedEventResult = SharedEvent

func (c *Client) CreateSharedEvent(ctx context.Context, params CreateSharedEventParams) (*CreateSharedEventResult, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	if params.LinkToEventID != nil {
		query.Set("linkToEventId", fmt.Sprint(*params.LinkToEventID))
	}
	var out CreateSharedEventResult
	if err := c.do(ctx, "POST", "/api/v1/shared-event", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type CreateWorkoutParams struct {
	ID   string
	Body WorkoutEx
}

type CreateWorkoutResult = Workout

func (c *Client) CreateWorkout(ctx context.Context, params CreateWorkoutParams) (*CreateWorkoutResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out CreateWorkoutResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/workouts", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteActivityParams struct {
	ID string
}

type DeleteActivityResult = ActivityId

func (c *Client) DeleteActivity(ctx context.Context, params DeleteActivityParams) (*DeleteActivityResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out DeleteActivityResult
	if err := c.do(ctx, "DELETE", "/api/v1/activity/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteCustomItemParams struct {
	ID     string
	ItemID int32
}

type DeleteCustomItemResult = struct{}

func (c *Client) DeleteCustomItem(ctx context.Context, params DeleteCustomItemParams) (*DeleteCustomItemResult, error) {
	pathParams := map[string]string{
		"id":     c.athleteIDOr(params.ID),
		"itemId": fmt.Sprint(params.ItemID),
	}
	query := url.Values{}
	var out DeleteCustomItemResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/custom-item/{itemId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteEventParams struct {
	EventID   int32
	ID        string
	NotBefore *string
	Others    *bool
}

type DeleteEventResult = DeleteEventResultBody

func (c *Client) DeleteEvent(ctx context.Context, params DeleteEventParams) (*DeleteEventResult, error) {
	pathParams := map[string]string{
		"eventId": fmt.Sprint(params.EventID),
		"id":      c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.NotBefore != nil {
		query.Set("notBefore", fmt.Sprint(*params.NotBefore))
	}
	if params.Others != nil {
		query.Set("others", fmt.Sprint(*params.Others))
	}
	var out DeleteEventResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/events/{eventId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteEventsParams struct {
	ID          string
	Category    []string
	CreatedByID *string
	Newest      *string
	Oldest      string
}

type DeleteEventsResult = struct{}

func (c *Client) DeleteEvents(ctx context.Context, params DeleteEventsParams) (*DeleteEventsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	for _, v := range params.Category {
		query.Add("category", fmt.Sprint(v))
	}
	if params.CreatedByID != nil {
		query.Set("createdById", fmt.Sprint(*params.CreatedByID))
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	query.Set("oldest", fmt.Sprint(params.Oldest))
	var out DeleteEventsResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/events", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteEventsBulkParams struct {
	ID   string
	Body DeleteEventsBulkRequestBody
}

type DeleteEventsBulkResult = DeleteEventsResponse

func (c *Client) DeleteEventsBulk(ctx context.Context, params DeleteEventsBulkParams) (*DeleteEventsBulkResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DeleteEventsBulkResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/events/bulk-delete", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteFolderParams struct {
	FolderID int32
	ID       string
}

type DeleteFolderResult = DeleteFolderResultBody

func (c *Client) DeleteFolder(ctx context.Context, params DeleteFolderParams) (*DeleteFolderResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DeleteFolderResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/folders/{folderId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteGearParams struct {
	GearID string
	ID     string
}

type DeleteGearResult = struct{}

func (c *Client) DeleteGear(ctx context.Context, params DeleteGearParams) (*DeleteGearResult, error) {
	pathParams := map[string]string{
		"gearId": fmt.Sprint(params.GearID),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DeleteGearResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/gear/{gearId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteIntervalsParams struct {
	ID   string
	Body DeleteIntervalsRequestBody
}

type DeleteIntervalsResult = IntervalsDTO

func (c *Client) DeleteIntervals(ctx context.Context, params DeleteIntervalsParams) (*DeleteIntervalsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out DeleteIntervalsResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}/delete-intervals", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteMessageParams struct {
	ID    int32
	MsgID int64
}

type DeleteMessageResult = DeleteMessageResultBody

func (c *Client) DeleteMessage(ctx context.Context, params DeleteMessageParams) (*DeleteMessageResult, error) {
	pathParams := map[string]string{
		"id":    fmt.Sprint(params.ID),
		"msgId": fmt.Sprint(params.MsgID),
	}
	query := url.Values{}
	var out DeleteMessageResult
	if err := c.do(ctx, "DELETE", "/api/v1/chats/{id}/messages/{msgId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteReminderParams struct {
	GearID     string
	ID         string
	ReminderID int32
}

type DeleteReminderResult = Gear

func (c *Client) DeleteReminder(ctx context.Context, params DeleteReminderParams) (*DeleteReminderResult, error) {
	pathParams := map[string]string{
		"gearId":     fmt.Sprint(params.GearID),
		"id":         c.athleteIDOr(params.ID),
		"reminderId": fmt.Sprint(params.ReminderID),
	}
	query := url.Values{}
	var out DeleteReminderResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/gear/{gearId}/reminder/{reminderId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteSettingsParams struct {
	AthleteID string
	ID        int32
}

type DeleteSettingsResult = DeleteSettingsResultBody

func (c *Client) DeleteSettings(ctx context.Context, params DeleteSettingsParams) (*DeleteSettingsResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out DeleteSettingsResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{athleteId}/sport-settings/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteSharedEventParams struct {
	ID int32
}

type DeleteSharedEventResult = struct{}

func (c *Client) DeleteSharedEvent(ctx context.Context, params DeleteSharedEventParams) (*DeleteSharedEventResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out DeleteSharedEventResult
	if err := c.do(ctx, "DELETE", "/api/v1/shared-event/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DeleteWorkoutParams struct {
	ID        string
	WorkoutID int32
	Others    *bool
}

type DeleteWorkoutResult = DeleteWorkoutResultBody

func (c *Client) DeleteWorkout(ctx context.Context, params DeleteWorkoutParams) (*DeleteWorkoutResult, error) {
	pathParams := map[string]string{
		"id":        c.athleteIDOr(params.ID),
		"workoutId": fmt.Sprint(params.WorkoutID),
	}
	query := url.Values{}
	if params.Others != nil {
		query.Set("others", fmt.Sprint(*params.Others))
	}
	var out DeleteWorkoutResult
	if err := c.do(ctx, "DELETE", "/api/v1/athlete/{id}/workouts/{workoutId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DisconnectAppParams struct {
}

type DisconnectAppResult = struct{}

func (c *Client) DisconnectApp(ctx context.Context, params DisconnectAppParams) (*DisconnectAppResult, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	var out DisconnectAppResult
	if err := c.do(ctx, "DELETE", "/api/v1/disconnect-app", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadActivitiesAsCsvParams struct {
	ID string
}

type DownloadActivitiesAsCsvResult = struct{}

func (c *Client) DownloadActivitiesAsCsv(ctx context.Context, params DownloadActivitiesAsCsvParams) (*DownloadActivitiesAsCsvResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DownloadActivitiesAsCsvResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities.csv", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadActivityFileParams struct {
	ID string
}

type DownloadActivityFileResult = struct{}

func (c *Client) DownloadActivityFile(ctx context.Context, params DownloadActivityFileParams) (*DownloadActivityFileResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out DownloadActivityFileResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/file", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadActivityFitFileParams struct {
	ID    string
	HR    *bool
	Power *bool
}

type DownloadActivityFitFileResult = struct{}

func (c *Client) DownloadActivityFitFile(ctx context.Context, params DownloadActivityFitFileParams) (*DownloadActivityFitFileResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.HR != nil {
		query.Set("hr", fmt.Sprint(*params.HR))
	}
	if params.Power != nil {
		query.Set("power", fmt.Sprint(*params.Power))
	}
	var out DownloadActivityFitFileResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/fit-file", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadActivityFitFilesParams struct {
	ID    string
	HR    *bool
	Ids   []string
	Power *bool
}

type DownloadActivityFitFilesResult = struct{}

func (c *Client) DownloadActivityFitFiles(ctx context.Context, params DownloadActivityFitFilesParams) (*DownloadActivityFitFilesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.HR != nil {
		query.Set("hr", fmt.Sprint(*params.HR))
	}
	for _, v := range params.Ids {
		query.Add("ids", fmt.Sprint(v))
	}
	if params.Power != nil {
		query.Set("power", fmt.Sprint(*params.Power))
	}
	var out DownloadActivityFitFilesResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/download-fit-files", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadActivityGpxFileParams struct {
	ID    string
	HR    *bool
	Power *bool
}

type DownloadActivityGpxFileResult = struct{}

func (c *Client) DownloadActivityGpxFile(ctx context.Context, params DownloadActivityGpxFileParams) (*DownloadActivityGpxFileResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.HR != nil {
		query.Set("hr", fmt.Sprint(*params.HR))
	}
	if params.Power != nil {
		query.Set("power", fmt.Sprint(*params.Power))
	}
	var out DownloadActivityGpxFileResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/gpx-file", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadWorkoutParams struct {
	Ext  string
	Body Workout
}

type DownloadWorkoutResult = struct{}

func (c *Client) DownloadWorkout(ctx context.Context, params DownloadWorkoutParams) (*DownloadWorkoutResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
	}
	query := url.Values{}
	var out DownloadWorkoutResult
	if err := c.do(ctx, "POST", "/api/v1/download-workout{ext}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadWorkout1Params struct {
	EventID int32
	Ext     string
	ID      string
}

type DownloadWorkout1Result = struct{}

func (c *Client) DownloadWorkout1(ctx context.Context, params DownloadWorkout1Params) (*DownloadWorkout1Result, error) {
	pathParams := map[string]string{
		"eventId": fmt.Sprint(params.EventID),
		"ext":     fmt.Sprint(params.Ext),
		"id":      c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DownloadWorkout1Result
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/events/{eventId}/download{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadWorkoutForAthleteParams struct {
	Ext  string
	ID   string
	Body Workout
}

type DownloadWorkoutForAthleteResult = struct{}

func (c *Client) DownloadWorkoutForAthlete(ctx context.Context, params DownloadWorkoutForAthleteParams) (*DownloadWorkoutForAthleteResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DownloadWorkoutForAthleteResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/download-workout{ext}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DownloadWorkoutsParams struct {
	ID         string
	Ext        string
	HRRange    *float64
	Locale     *string
	Newest     string
	Oldest     string
	PaceRange  *float64
	PowerRange *float64
}

type DownloadWorkoutsResult = struct{}

func (c *Client) DownloadWorkouts(ctx context.Context, params DownloadWorkoutsParams) (*DownloadWorkoutsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("ext", fmt.Sprint(params.Ext))
	if params.HRRange != nil {
		query.Set("hrRange", fmt.Sprint(*params.HRRange))
	}
	if params.Locale != nil {
		query.Set("locale", fmt.Sprint(*params.Locale))
	}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	if params.PaceRange != nil {
		query.Set("paceRange", fmt.Sprint(*params.PaceRange))
	}
	if params.PowerRange != nil {
		query.Set("powerRange", fmt.Sprint(*params.PowerRange))
	}
	var out DownloadWorkoutsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/workouts.zip", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DuplicateEventsParams struct {
	ID   string
	Body DuplicateEventsDTO
}

type DuplicateEventsResult = DuplicateEventsResultBody

func (c *Client) DuplicateEvents(ctx context.Context, params DuplicateEventsParams) (*DuplicateEventsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DuplicateEventsResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/duplicate-events", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type DuplicateWorkoutsParams struct {
	ID   string
	Body DuplicateWorkoutsDTO
}

type DuplicateWorkoutsResult = DuplicateWorkoutsResultBody

func (c *Client) DuplicateWorkouts(ctx context.Context, params DuplicateWorkoutsParams) (*DuplicateWorkoutsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out DuplicateWorkoutsResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/duplicate-workouts", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type FindBestEffortsParams struct {
	ID               string
	Count            *int32
	Distance         *float64
	Duration         *int32
	EndIndex         *int32
	ExcludeIntervals *bool
	MinValue         *float64
	StartIndex       *int32
	Stream           string
}

type FindBestEffortsResult = BestEfforts

func (c *Client) FindBestEfforts(ctx context.Context, params FindBestEffortsParams) (*FindBestEffortsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.Count != nil {
		query.Set("count", fmt.Sprint(*params.Count))
	}
	if params.Distance != nil {
		query.Set("distance", fmt.Sprint(*params.Distance))
	}
	if params.Duration != nil {
		query.Set("duration", fmt.Sprint(*params.Duration))
	}
	if params.EndIndex != nil {
		query.Set("endIndex", fmt.Sprint(*params.EndIndex))
	}
	if params.ExcludeIntervals != nil {
		query.Set("excludeIntervals", fmt.Sprint(*params.ExcludeIntervals))
	}
	if params.MinValue != nil {
		query.Set("minValue", fmt.Sprint(*params.MinValue))
	}
	if params.StartIndex != nil {
		query.Set("startIndex", fmt.Sprint(*params.StartIndex))
	}
	query.Set("stream", fmt.Sprint(params.Stream))
	var out FindBestEffortsResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/best-efforts", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivitiesParams struct {
	AthleteID string
	Ids       []string
	Intervals *bool
}

type GetActivitiesResult = GetActivitiesResultBody

func (c *Client) GetActivities(ctx context.Context, params GetActivitiesParams) (*GetActivitiesResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"ids":       fmt.Sprint(params.Ids),
	}
	query := url.Values{}
	if params.Intervals != nil {
		query.Set("intervals", fmt.Sprint(*params.Intervals))
	}
	var out GetActivitiesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{athleteId}/activities/{ids}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityParams struct {
	ID        string
	Intervals *bool
}

type GetActivityResult = GetActivityResultBody

func (c *Client) GetActivity(ctx context.Context, params GetActivityParams) (*GetActivityResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.Intervals != nil {
		query.Set("intervals", fmt.Sprint(*params.Intervals))
	}
	var out GetActivityResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityHrcurveParams struct {
	Ext string
	ID  string
}

type GetActivityHrcurveResult = HRCurve

func (c *Client) GetActivityHrcurve(ctx context.Context, params GetActivityHrcurveParams) (*GetActivityHrcurveResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetActivityHrcurveResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/hr-curve{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityMapParams struct {
	ID         string
	Bounds     []float64
	BoundsOnly *bool
	Weather    *bool
}

type GetActivityMapResult = MapData

func (c *Client) GetActivityMap(ctx context.Context, params GetActivityMapParams) (*GetActivityMapResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if len(params.Bounds) > 0 {
		for _, v := range params.Bounds {
			query.Add("bounds", fmt.Sprint(v))
		}
	}
	if params.BoundsOnly != nil {
		query.Set("boundsOnly", fmt.Sprint(*params.BoundsOnly))
	}
	if params.Weather != nil {
		query.Set("weather", fmt.Sprint(*params.Weather))
	}
	var out GetActivityMapResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/map", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityPaceCurveParams struct {
	Ext string
	ID  string
	Gap *bool
}

type GetActivityPaceCurveResult = PaceCurve

func (c *Client) GetActivityPaceCurve(ctx context.Context, params GetActivityPaceCurveParams) (*GetActivityPaceCurveResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.Gap != nil {
		query.Set("gap", fmt.Sprint(*params.Gap))
	}
	var out GetActivityPaceCurveResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/pace-curve{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityPowerCurveParams struct {
	Ext     string
	ID      string
	Fatigue *string
}

type GetActivityPowerCurveResult = PowerCurve

func (c *Client) GetActivityPowerCurve(ctx context.Context, params GetActivityPowerCurveParams) (*GetActivityPowerCurveResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.Fatigue != nil {
		query.Set("fatigue", fmt.Sprint(*params.Fatigue))
	}
	var out GetActivityPowerCurveResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/power-curve{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityPowerSpikeModelParams struct {
	ID string
}

type GetActivityPowerSpikeModelResult = PowerModel

func (c *Client) GetActivityPowerSpikeModel(ctx context.Context, params GetActivityPowerSpikeModelParams) (*GetActivityPowerSpikeModelResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetActivityPowerSpikeModelResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/power-spike-model", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivitySegmentsParams struct {
	ID string
}

type GetActivitySegmentsResult = GetActivitySegmentsResultBody

func (c *Client) GetActivitySegments(ctx context.Context, params GetActivitySegmentsParams) (*GetActivitySegmentsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetActivitySegmentsResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/segments", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityStreamsParams struct {
	Ext             string
	ID              string
	IncludeDefaults *bool
	Types           []string
}

type GetActivityStreamsResult = GetActivityStreamsResultBody

func (c *Client) GetActivityStreams(ctx context.Context, params GetActivityStreamsParams) (*GetActivityStreamsResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.IncludeDefaults != nil {
		query.Set("includeDefaults", fmt.Sprint(*params.IncludeDefaults))
	}
	if len(params.Types) > 0 {
		for _, v := range params.Types {
			query.Add("types", fmt.Sprint(v))
		}
	}
	var out GetActivityStreamsResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/streams{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetActivityWeatherSummaryParams struct {
	ID         string
	EndIndex   *int32
	StartIndex *int32
}

type GetActivityWeatherSummaryResult = ActivityWeatherSummary

func (c *Client) GetActivityWeatherSummary(ctx context.Context, params GetActivityWeatherSummaryParams) (*GetActivityWeatherSummaryResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.EndIndex != nil {
		query.Set("end_index", fmt.Sprint(*params.EndIndex))
	}
	if params.StartIndex != nil {
		query.Set("start_index", fmt.Sprint(*params.StartIndex))
	}
	var out GetActivityWeatherSummaryResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/weather-summary", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteParams struct {
	ID string
}

type GetAthleteResult = WithSportSettings

func (c *Client) GetAthlete(ctx context.Context, params GetAthleteParams) (*GetAthleteResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetAthleteResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteMmpmodelParams struct {
	ID   string
	Type string
}

type GetAthleteMmpmodelResult = PowerModel

func (c *Client) GetAthleteMmpmodel(ctx context.Context, params GetAthleteMmpmodelParams) (*GetAthleteMmpmodelResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("type", fmt.Sprint(params.Type))
	var out GetAthleteMmpmodelResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/mmp-model", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteProfileParams struct {
	ID string
}

type GetAthleteProfileResult = AthleteProfile

func (c *Client) GetAthleteProfile(ctx context.Context, params GetAthleteProfileParams) (*GetAthleteProfileResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetAthleteProfileResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/profile", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteRouteParams struct {
	ID          string
	RouteID     int64
	IncludePath *bool
}

type GetAthleteRouteResult = AthleteRoute

func (c *Client) GetAthleteRoute(ctx context.Context, params GetAthleteRouteParams) (*GetAthleteRouteResult, error) {
	pathParams := map[string]string{
		"id":       c.athleteIDOr(params.ID),
		"route_id": fmt.Sprint(params.RouteID),
	}
	query := url.Values{}
	if params.IncludePath != nil {
		query.Set("includePath", fmt.Sprint(*params.IncludePath))
	}
	var out GetAthleteRouteResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/routes/{route_id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteSummaryParams struct {
	Ext   string
	ID    string
	End   *string
	Start *string
	Tags  []string
}

type GetAthleteSummaryResult = GetAthleteSummaryResultBody

func (c *Client) GetAthleteSummary(ctx context.Context, params GetAthleteSummaryParams) (*GetAthleteSummaryResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.End != nil {
		query.Set("end", fmt.Sprint(*params.End))
	}
	if params.Start != nil {
		query.Set("start", fmt.Sprint(*params.Start))
	}
	if len(params.Tags) > 0 {
		for _, v := range params.Tags {
			query.Add("tags", fmt.Sprint(v))
		}
	}
	var out GetAthleteSummaryResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/athlete-summary{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetAthleteTrainingPlanParams struct {
	ID string
}

type GetAthleteTrainingPlanResult = AthleteTrainingPlan

func (c *Client) GetAthleteTrainingPlan(ctx context.Context, params GetAthleteTrainingPlanParams) (*GetAthleteTrainingPlanResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetAthleteTrainingPlanResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/training-plan", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetCustomItemParams struct {
	ID     string
	ItemID int32
}

type GetCustomItemResult = CustomItem

func (c *Client) GetCustomItem(ctx context.Context, params GetCustomItemParams) (*GetCustomItemResult, error) {
	pathParams := map[string]string{
		"id":     c.athleteIDOr(params.ID),
		"itemId": fmt.Sprint(params.ItemID),
	}
	query := url.Values{}
	var out GetCustomItemResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/custom-item/{itemId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetForecastParams struct {
	ID string
}

type GetForecastResult = WeatherDTO

func (c *Client) GetForecast(ctx context.Context, params GetForecastParams) (*GetForecastResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetForecastResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/weather-forecast", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetGapHistogramParams struct {
	ID string
}

type GetGapHistogramResult = GetGapHistogramResultBody

func (c *Client) GetGapHistogram(ctx context.Context, params GetGapHistogramParams) (*GetGapHistogramResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetGapHistogramResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/gap-histogram", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetHrhistogramParams struct {
	ID         string
	BucketSize *int32
}

type GetHrhistogramResult = GetHrhistogramResultBody

func (c *Client) GetHrhistogram(ctx context.Context, params GetHrhistogramParams) (*GetHrhistogramResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.BucketSize != nil {
		query.Set("bucketSize", fmt.Sprint(*params.BucketSize))
	}
	var out GetHrhistogramResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/hr-histogram", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetHrtrainingLoadModelParams struct {
	ID string
}

type GetHrtrainingLoadModelResult = HRLoadModel

func (c *Client) GetHrtrainingLoadModel(ctx context.Context, params GetHrtrainingLoadModelParams) (*GetHrtrainingLoadModelResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetHrtrainingLoadModelResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/hr-load-model", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetIntervalStatsParams struct {
	ID         string
	EndIndex   int32
	StartIndex int32
}

type GetIntervalStatsResult = Interval

func (c *Client) GetIntervalStats(ctx context.Context, params GetIntervalStatsParams) (*GetIntervalStatsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	query.Set("end_index", fmt.Sprint(params.EndIndex))
	query.Set("start_index", fmt.Sprint(params.StartIndex))
	var out GetIntervalStatsResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/interval-stats", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetIntervalsParams struct {
	ID string
}

type GetIntervalsResult = IntervalsDTO

func (c *Client) GetIntervals(ctx context.Context, params GetIntervalsParams) (*GetIntervalsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetIntervalsResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/intervals", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetPaceHistogramParams struct {
	ID string
}

type GetPaceHistogramResult = GetPaceHistogramResultBody

func (c *Client) GetPaceHistogram(ctx context.Context, params GetPaceHistogramParams) (*GetPaceHistogramResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetPaceHistogramResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/pace-histogram", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetPowerHistogramParams struct {
	ID         string
	BucketSize *int32
}

type GetPowerHistogramResult = GetPowerHistogramResultBody

func (c *Client) GetPowerHistogram(ctx context.Context, params GetPowerHistogramParams) (*GetPowerHistogramResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.BucketSize != nil {
		query.Set("bucketSize", fmt.Sprint(*params.BucketSize))
	}
	var out GetPowerHistogramResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/power-histogram", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetPowerHrcurveParams struct {
	ID    string
	End   string
	Start string
}

type GetPowerHrcurveResult = PowerHRCurve

func (c *Client) GetPowerHrcurve(ctx context.Context, params GetPowerHrcurveParams) (*GetPowerHrcurveResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("end", fmt.Sprint(params.End))
	query.Set("start", fmt.Sprint(params.Start))
	var out GetPowerHrcurveResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/power-hr-curve", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetPowerVsHRParams struct {
	Ext string
	ID  string
}

type GetPowerVsHRResult = PowerVsHRPlot

func (c *Client) GetPowerVsHR(ctx context.Context, params GetPowerVsHRParams) (*GetPowerVsHRResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetPowerVsHRResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/power-vs-hr{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetRecordParams struct {
	Date string
	ID   string
}

type GetRecordResult = Wellness

func (c *Client) GetRecord(ctx context.Context, params GetRecordParams) (*GetRecordResult, error) {
	pathParams := map[string]string{
		"date": fmt.Sprint(params.Date),
		"id":   c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetRecordResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/wellness/{date}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetSettingsParams struct {
	DeviceClass string
	ID          string
}

type GetSettingsResult = GetSettingsResultBody

func (c *Client) GetSettings(ctx context.Context, params GetSettingsParams) (*GetSettingsResult, error) {
	pathParams := map[string]string{
		"deviceClass": fmt.Sprint(params.DeviceClass),
		"id":          c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetSettingsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/settings/{deviceClass}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetSettings1Params struct {
	AthleteID string
	ID        string
}

type GetSettings1Result = SportSettings

func (c *Client) GetSettings1(ctx context.Context, params GetSettings1Params) (*GetSettings1Result, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetSettings1Result
	if err := c.do(ctx, "GET", "/api/v1/athlete/{athleteId}/sport-settings/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetSharedEventParams struct {
	ID int32
}

type GetSharedEventResult = SharedEvent

func (c *Client) GetSharedEvent(ctx context.Context, params GetSharedEventParams) (*GetSharedEventResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetSharedEventResult
	if err := c.do(ctx, "GET", "/api/v1/shared-event/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetTimeAtHRParams struct {
	ID string
}

type GetTimeAtHRResult = Plot

func (c *Client) GetTimeAtHR(ctx context.Context, params GetTimeAtHRParams) (*GetTimeAtHRResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out GetTimeAtHRResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/time-at-hr", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type GetWeatherConfigParams struct {
	ID string
}

type GetWeatherConfigResult = WeatherConfig

func (c *Client) GetWeatherConfig(ctx context.Context, params GetWeatherConfigParams) (*GetWeatherConfigResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out GetWeatherConfigResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/weather-config", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ImportWorkoutFileParams struct {
	FolderID  int32
	ID        string
	AthleteID *string
	Type      string
	Body      *ImportWorkoutFileRequestBody
}

type ImportWorkoutFileResult = Workout

func (c *Client) ImportWorkoutFile(ctx context.Context, params ImportWorkoutFileParams) (*ImportWorkoutFileResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.AthleteID != nil {
		query.Set("athleteId", fmt.Sprint(*params.AthleteID))
	}
	query.Set("type", fmt.Sprint(params.Type))
	var out ImportWorkoutFileResult
	if err := c.doMultipart(ctx, "POST", "/api/v1/athlete/{id}/folders/{folderId}/import-workout", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivitiesParams struct {
	ID      string
	Fields  []string
	Limit   *int32
	Newest  *string
	Oldest  string
	RouteID *int64
}

type ListActivitiesResult = ListActivitiesResultBody

func (c *Client) ListActivities(ctx context.Context, params ListActivitiesParams) (*ListActivitiesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Fields) > 0 {
		for _, v := range params.Fields {
			query.Add("fields", fmt.Sprint(v))
		}
	}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	query.Set("oldest", fmt.Sprint(params.Oldest))
	if params.RouteID != nil {
		query.Set("route_id", fmt.Sprint(*params.RouteID))
	}
	var out ListActivitiesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivitiesAroundParams struct {
	ID         string
	ActivityID string
	Limit      *int32
	RouteID    *int64
}

type ListActivitiesAroundResult = ListActivitiesAroundResultBody

func (c *Client) ListActivitiesAround(ctx context.Context, params ListActivitiesAroundParams) (*ListActivitiesAroundResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("activity_id", fmt.Sprint(params.ActivityID))
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	if params.RouteID != nil {
		query.Set("route_id", fmt.Sprint(*params.RouteID))
	}
	var out ListActivitiesAroundResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities-around", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivityHrcurvesParams struct {
	Ext     string
	ID      string
	Filters []ActivityFilter
	Newest  string
	Oldest  string
	Secs    []int32
	Type    *string
}

type ListActivityHrcurvesResult = ActivityHRCurvePayload

func (c *Client) ListActivityHrcurves(ctx context.Context, params ListActivityHrcurvesParams) (*ListActivityHrcurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	if len(params.Secs) > 0 {
		for _, v := range params.Secs {
			query.Add("secs", fmt.Sprint(v))
		}
	}
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out ListActivityHrcurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activity-hr-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivityMessagesParams struct {
	ID      string
	Limit   *int32
	SinceID *int64
}

type ListActivityMessagesResult = ListActivityMessagesResultBody

func (c *Client) ListActivityMessages(ctx context.Context, params ListActivityMessagesParams) (*ListActivityMessagesResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	if params.SinceID != nil {
		query.Set("sinceId", fmt.Sprint(*params.SinceID))
	}
	var out ListActivityMessagesResult
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/messages", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivityPaceCurvesParams struct {
	Ext       string
	ID        string
	Distances []float64
	Filters   []ActivityFilter
	Gap       *bool
	Newest    string
	Oldest    string
	Type      *string
}

type ListActivityPaceCurvesResult = struct{}

func (c *Client) ListActivityPaceCurves(ctx context.Context, params ListActivityPaceCurvesParams) (*ListActivityPaceCurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Distances) > 0 {
		for _, v := range params.Distances {
			query.Add("distances", fmt.Sprint(v))
		}
	}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	if params.Gap != nil {
		query.Set("gap", fmt.Sprint(*params.Gap))
	}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out ListActivityPaceCurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activity-pace-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivityPowerCurvesParams struct {
	Ext     string
	ID      string
	Fatigue *string
	Filters []ActivityFilter
	Newest  string
	Oldest  string
	Secs    []int32
	Type    *string
}

type ListActivityPowerCurvesResult = ActivityPowerCurvePayload

func (c *Client) ListActivityPowerCurves(ctx context.Context, params ListActivityPowerCurvesParams) (*ListActivityPowerCurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.Fatigue != nil {
		query.Set("fatigue", fmt.Sprint(*params.Fatigue))
	}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	if len(params.Secs) > 0 {
		for _, v := range params.Secs {
			query.Add("secs", fmt.Sprint(v))
		}
	}
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out ListActivityPowerCurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activity-power-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListActivityPowerCurves1Params struct {
	Ext     string
	ID      string
	Fatigue []string
	Types   []string
}

type ListActivityPowerCurves1Result = ListActivityPowerCurves1ResultBody

func (c *Client) ListActivityPowerCurves1(ctx context.Context, params ListActivityPowerCurves1Params) (*ListActivityPowerCurves1Result, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if len(params.Fatigue) > 0 {
		for _, v := range params.Fatigue {
			query.Add("fatigue", fmt.Sprint(v))
		}
	}
	if len(params.Types) > 0 {
		for _, v := range params.Types {
			query.Add("types", fmt.Sprint(v))
		}
	}
	var out ListActivityPowerCurves1Result
	if err := c.do(ctx, "GET", "/api/v1/activity/{id}/power-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListAthleteHrcurvesParams struct {
	Ext           string
	ID            string
	Curves        []string
	F1            []ActivityFilter
	F2            []ActivityFilter
	F3            []ActivityFilter
	Filters       []ActivityFilter
	Newest        *string
	Now           *string
	SubMaxEfforts *int32
	Type          *string
}

type ListAthleteHrcurvesResult = DataCurveSetHRCurve

func (c *Client) ListAthleteHrcurves(ctx context.Context, params ListAthleteHrcurvesParams) (*ListAthleteHrcurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Curves) > 0 {
		for _, v := range params.Curves {
			query.Add("curves", fmt.Sprint(v))
		}
	}
	for _, v := range params.F1 {
		query.Add("f1", fmt.Sprint(v))
	}
	for _, v := range params.F2 {
		query.Add("f2", fmt.Sprint(v))
	}
	for _, v := range params.F3 {
		query.Add("f3", fmt.Sprint(v))
	}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	if params.Now != nil {
		query.Set("now", fmt.Sprint(*params.Now))
	}
	if params.SubMaxEfforts != nil {
		query.Set("subMaxEfforts", fmt.Sprint(*params.SubMaxEfforts))
	}
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out ListAthleteHrcurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/hr-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListAthletePaceCurvesParams struct {
	Ext           string
	ID            string
	Curves        []string
	F1            []ActivityFilter
	F2            []ActivityFilter
	F3            []ActivityFilter
	Filters       []ActivityFilter
	Gap           *bool
	IncludeRanks  *bool
	Newest        *string
	Now           *string
	PmType        *string
	SubMaxEfforts *int32
	Type          *string
}

type ListAthletePaceCurvesResult = DataCurveSetPaceCurve

func (c *Client) ListAthletePaceCurves(ctx context.Context, params ListAthletePaceCurvesParams) (*ListAthletePaceCurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Curves) > 0 {
		for _, v := range params.Curves {
			query.Add("curves", fmt.Sprint(v))
		}
	}
	for _, v := range params.F1 {
		query.Add("f1", fmt.Sprint(v))
	}
	for _, v := range params.F2 {
		query.Add("f2", fmt.Sprint(v))
	}
	for _, v := range params.F3 {
		query.Add("f3", fmt.Sprint(v))
	}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	if params.Gap != nil {
		query.Set("gap", fmt.Sprint(*params.Gap))
	}
	if params.IncludeRanks != nil {
		query.Set("includeRanks", fmt.Sprint(*params.IncludeRanks))
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	if params.Now != nil {
		query.Set("now", fmt.Sprint(*params.Now))
	}
	if params.PmType != nil {
		query.Set("pmType", fmt.Sprint(*params.PmType))
	}
	if params.SubMaxEfforts != nil {
		query.Set("subMaxEfforts", fmt.Sprint(*params.SubMaxEfforts))
	}
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out ListAthletePaceCurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/pace-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListAthletePowerCurvesParams struct {
	Ext           string
	ID            string
	Curves        []string
	F1            []ActivityFilter
	F2            []ActivityFilter
	F3            []ActivityFilter
	Filters       []ActivityFilter
	IncludeRanks  *bool
	Newest        *string
	Now           *string
	PmType        *string
	SubMaxEfforts *int32
	Type          string
}

type ListAthletePowerCurvesResult = DataCurveSetPowerCurve

func (c *Client) ListAthletePowerCurves(ctx context.Context, params ListAthletePowerCurvesParams) (*ListAthletePowerCurvesResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Curves) > 0 {
		for _, v := range params.Curves {
			query.Add("curves", fmt.Sprint(v))
		}
	}
	for _, v := range params.F1 {
		query.Add("f1", fmt.Sprint(v))
	}
	for _, v := range params.F2 {
		query.Add("f2", fmt.Sprint(v))
	}
	for _, v := range params.F3 {
		query.Add("f3", fmt.Sprint(v))
	}
	if len(params.Filters) > 0 {
		for _, v := range params.Filters {
			query.Add("filters", fmt.Sprint(v))
		}
	}
	if params.IncludeRanks != nil {
		query.Set("includeRanks", fmt.Sprint(*params.IncludeRanks))
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	if params.Now != nil {
		query.Set("now", fmt.Sprint(*params.Now))
	}
	if params.PmType != nil {
		query.Set("pmType", fmt.Sprint(*params.PmType))
	}
	if params.SubMaxEfforts != nil {
		query.Set("subMaxEfforts", fmt.Sprint(*params.SubMaxEfforts))
	}
	query.Set("type", fmt.Sprint(params.Type))
	var out ListAthletePowerCurvesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/power-curves{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListAthleteRoutesParams struct {
	ID string
}

type ListAthleteRoutesResult = ListAthleteRoutesResultBody

func (c *Client) ListAthleteRoutes(ctx context.Context, params ListAthleteRoutesParams) (*ListAthleteRoutesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListAthleteRoutesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/routes", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListChatsParams struct {
	ID string
}

type ListChatsResult = ListChatsResultBody

func (c *Client) ListChats(ctx context.Context, params ListChatsParams) (*ListChatsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListChatsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/chats", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListCustomItemsParams struct {
	ID string
}

type ListCustomItemsResult = ListCustomItemsResultBody

func (c *Client) ListCustomItems(ctx context.Context, params ListCustomItemsParams) (*ListCustomItemsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListCustomItemsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/custom-item", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListEventsParams struct {
	Format     string
	ID         string
	CalendarID *int32
	Category   []string
	Ext        *string
	HRRange    *float64
	Limit      *int32
	Locale     *string
	Newest     *string
	Oldest     *string
	PaceRange  *float64
	PowerRange *float64
	Resolve    *bool
}

type ListEventsResult = ListEventsResultBody

func (c *Client) ListEvents(ctx context.Context, params ListEventsParams) (*ListEventsResult, error) {
	pathParams := map[string]string{
		"format": fmt.Sprint(params.Format),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.CalendarID != nil {
		query.Set("calendar_id", fmt.Sprint(*params.CalendarID))
	}
	if len(params.Category) > 0 {
		for _, v := range params.Category {
			query.Add("category", fmt.Sprint(v))
		}
	}
	if params.Ext != nil {
		query.Set("ext", fmt.Sprint(*params.Ext))
	}
	if params.HRRange != nil {
		query.Set("hrRange", fmt.Sprint(*params.HRRange))
	}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	if params.Locale != nil {
		query.Set("locale", fmt.Sprint(*params.Locale))
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	if params.Oldest != nil {
		query.Set("oldest", fmt.Sprint(*params.Oldest))
	}
	if params.PaceRange != nil {
		query.Set("paceRange", fmt.Sprint(*params.PaceRange))
	}
	if params.PowerRange != nil {
		query.Set("powerRange", fmt.Sprint(*params.PowerRange))
	}
	if params.Resolve != nil {
		query.Set("resolve", fmt.Sprint(*params.Resolve))
	}
	var out ListEventsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/events{format}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListFitnessModelEventsParams struct {
	ID string
}

type ListFitnessModelEventsResult = ListFitnessModelEventsResultBody

func (c *Client) ListFitnessModelEvents(ctx context.Context, params ListFitnessModelEventsParams) (*ListFitnessModelEventsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListFitnessModelEventsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/fitness-model-events", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListFolderSharedWithParams struct {
	FolderID int32
	ID       string
}

type ListFolderSharedWithResult = ListFolderSharedWithResultBody

func (c *Client) ListFolderSharedWith(ctx context.Context, params ListFolderSharedWithParams) (*ListFolderSharedWithResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListFolderSharedWithResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/folders/{folderId}/shared-with", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListFoldersParams struct {
	ID string
}

type ListFoldersResult = ListFoldersResultBody

func (c *Client) ListFolders(ctx context.Context, params ListFoldersParams) (*ListFoldersResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListFoldersResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/folders", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListGearParams struct {
	Ext string
	ID  string
}

type ListGearResult = ListGearResultBody

func (c *Client) ListGear(ctx context.Context, params ListGearParams) (*ListGearResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListGearResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/gear{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListMatchingActivitiesParams struct {
	AthleteID string
	ID        string
}

type ListMatchingActivitiesResult = ListMatchingActivitiesResultBody

func (c *Client) ListMatchingActivities(ctx context.Context, params ListMatchingActivitiesParams) (*ListMatchingActivitiesResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out ListMatchingActivitiesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{athleteId}/sport-settings/{id}/matching-activities", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListMessagesParams struct {
	ID       int32
	BeforeID *int64
	Limit    *int32
}

type ListMessagesResult = ListMessagesResultBody

func (c *Client) ListMessages(ctx context.Context, params ListMessagesParams) (*ListMessagesResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.BeforeID != nil {
		query.Set("beforeId", fmt.Sprint(*params.BeforeID))
	}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	var out ListMessagesResult
	if err := c.do(ctx, "GET", "/api/v1/chats/{id}/messages", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListPaceDistancesParams struct {
}

type ListPaceDistancesResult = PaceDistancesDTO

func (c *Client) ListPaceDistances(ctx context.Context, params ListPaceDistancesParams) (*ListPaceDistancesResult, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	var out ListPaceDistancesResult
	if err := c.do(ctx, "GET", "/api/v1/pace_distances", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListPaceDistancesForSportParams struct {
	AthleteID string
	ID        string
}

type ListPaceDistancesForSportResult = PaceDistancesDTO

func (c *Client) ListPaceDistancesForSport(ctx context.Context, params ListPaceDistancesForSportParams) (*ListPaceDistancesForSportResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out ListPaceDistancesForSportResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{athleteId}/sport-settings/{id}/pace_distances", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListSettingsParams struct {
	AthleteID string
}

type ListSettingsResult = ListSettingsResultBody

func (c *Client) ListSettings(ctx context.Context, params ListSettingsParams) (*ListSettingsResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
	}
	query := url.Values{}
	var out ListSettingsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{athleteId}/sport-settings", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListTagsParams struct {
	ID string
}

type ListTagsResult = ListTagsResultBody

func (c *Client) ListTags(ctx context.Context, params ListTagsParams) (*ListTagsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListTagsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/workout-tags", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListTags1Params struct {
	ID string
}

type ListTags1Result = ListTags1ResultBody

func (c *Client) ListTags1(ctx context.Context, params ListTags1Params) (*ListTags1Result, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListTags1Result
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/event-tags", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListTags2Params struct {
	ID string
}

type ListTags2Result = ListTags2ResultBody

func (c *Client) ListTags2(ctx context.Context, params ListTags2Params) (*ListTags2Result, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListTags2Result
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activity-tags", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListWellnessRecordsParams struct {
	Ext    string
	ID     string
	Cols   []string
	Fields []string
	Newest *string
	Oldest *string
}

type ListWellnessRecordsResult = ListWellnessRecordsResultBody

func (c *Client) ListWellnessRecords(ctx context.Context, params ListWellnessRecordsParams) (*ListWellnessRecordsResult, error) {
	pathParams := map[string]string{
		"ext": fmt.Sprint(params.Ext),
		"id":  c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if len(params.Cols) > 0 {
		for _, v := range params.Cols {
			query.Add("cols", fmt.Sprint(v))
		}
	}
	if len(params.Fields) > 0 {
		for _, v := range params.Fields {
			query.Add("fields", fmt.Sprint(v))
		}
	}
	if params.Newest != nil {
		query.Set("newest", fmt.Sprint(*params.Newest))
	}
	if params.Oldest != nil {
		query.Set("oldest", fmt.Sprint(*params.Oldest))
	}
	var out ListWellnessRecordsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/wellness{ext}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ListWorkoutsParams struct {
	ID string
}

type ListWorkoutsResult = ListWorkoutsResultBody

func (c *Client) ListWorkouts(ctx context.Context, params ListWorkoutsParams) (*ListWorkoutsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ListWorkoutsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/workouts", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type MarkEventAsDoneParams struct {
	EventID int32
	ID      string
}

type MarkEventAsDoneResult = Activity

func (c *Client) MarkEventAsDone(ctx context.Context, params MarkEventAsDoneParams) (*MarkEventAsDoneResult, error) {
	pathParams := map[string]string{
		"eventId": fmt.Sprint(params.EventID),
		"id":      c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out MarkEventAsDoneResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/events/{eventId}/mark-done", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ReplaceGearParams struct {
	GearID string
	ID     string
	Body   Gear
}

type ReplaceGearResult = ReplaceGearResultBody

func (c *Client) ReplaceGear(ctx context.Context, params ReplaceGearParams) (*ReplaceGearResult, error) {
	pathParams := map[string]string{
		"gearId": fmt.Sprint(params.GearID),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ReplaceGearResult
	if err := c.do(ctx, "POST", "/api/v1/athlete/{id}/gear/{gearId}/replace", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SearchForActivitiesParams struct {
	ID    string
	Limit *int32
	Q     string
}

type SearchForActivitiesResult = SearchForActivitiesResultBody

func (c *Client) SearchForActivities(ctx context.Context, params SearchForActivitiesParams) (*SearchForActivitiesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	query.Set("q", fmt.Sprint(params.Q))
	var out SearchForActivitiesResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities/search", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SearchForActivitiesFullParams struct {
	ID    string
	Limit *int32
	Q     string
}

type SearchForActivitiesFullResult = SearchForActivitiesFullResultBody

func (c *Client) SearchForActivitiesFull(ctx context.Context, params SearchForActivitiesFullParams) (*SearchForActivitiesFullResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	query.Set("q", fmt.Sprint(params.Q))
	var out SearchForActivitiesFullResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities/search-full", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SearchForIntervalsParams struct {
	ID           string
	Limit        *int32
	MaxIntensity int32
	MaxReps      *int32
	MaxSecs      int32
	MinIntensity int32
	MinReps      *int32
	MinSecs      int32
	Type         *string
}

type SearchForIntervalsResult = SearchForIntervalsResultBody

func (c *Client) SearchForIntervals(ctx context.Context, params SearchForIntervalsParams) (*SearchForIntervalsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.Limit != nil {
		query.Set("limit", fmt.Sprint(*params.Limit))
	}
	query.Set("maxIntensity", fmt.Sprint(params.MaxIntensity))
	if params.MaxReps != nil {
		query.Set("maxReps", fmt.Sprint(*params.MaxReps))
	}
	query.Set("maxSecs", fmt.Sprint(params.MaxSecs))
	query.Set("minIntensity", fmt.Sprint(params.MinIntensity))
	if params.MinReps != nil {
		query.Set("minReps", fmt.Sprint(*params.MinReps))
	}
	query.Set("minSecs", fmt.Sprint(params.MinSecs))
	if params.Type != nil {
		query.Set("type", fmt.Sprint(*params.Type))
	}
	var out SearchForIntervalsResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/activities/interval-search", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SendActivityMessageParams struct {
	ID   string
	Body NewActivityMsg
}

type SendActivityMessageResult = NewMsg

func (c *Client) SendActivityMessage(ctx context.Context, params SendActivityMessageParams) (*SendActivityMessageResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out SendActivityMessageResult
	if err := c.do(ctx, "POST", "/api/v1/activity/{id}/messages", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SendMessageParams struct {
	Body NewMessage
}

type SendMessageResult = SendResponse

func (c *Client) SendMessage(ctx context.Context, params SendMessageParams) (*SendMessageResult, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	var out SendMessageResult
	if err := c.do(ctx, "POST", "/api/v1/chats/send-message", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ShowChatParams struct {
	ID int32
}

type ShowChatResult = Chat

func (c *Client) ShowChat(ctx context.Context, params ShowChatParams) (*ShowChatResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out ShowChatResult
	if err := c.do(ctx, "GET", "/api/v1/chats/{id}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ShowEventParams struct {
	EventID int32
	ID      string
}

type ShowEventResult = Event

func (c *Client) ShowEvent(ctx context.Context, params ShowEventParams) (*ShowEventResult, error) {
	pathParams := map[string]string{
		"eventId": fmt.Sprint(params.EventID),
		"id":      c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out ShowEventResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/events/{eventId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type ShowWorkoutParams struct {
	ID        string
	WorkoutID int32
}

type ShowWorkoutResult = Workout

func (c *Client) ShowWorkout(ctx context.Context, params ShowWorkoutParams) (*ShowWorkoutResult, error) {
	pathParams := map[string]string{
		"id":        c.athleteIDOr(params.ID),
		"workoutId": fmt.Sprint(params.WorkoutID),
	}
	query := url.Values{}
	var out ShowWorkoutResult
	if err := c.do(ctx, "GET", "/api/v1/athlete/{id}/workouts/{workoutId}", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type SplitIntervalParams struct {
	ID      string
	SplitAt int32
}

type SplitIntervalResult = IntervalsDTO

func (c *Client) SplitInterval(ctx context.Context, params SplitIntervalParams) (*SplitIntervalResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	query.Set("splitAt", fmt.Sprint(params.SplitAt))
	var out SplitIntervalResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}/split-interval", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateActivityParams struct {
	ID   string
	Body Activity
}

type UpdateActivityResult = Activity

func (c *Client) UpdateActivity(ctx context.Context, params UpdateActivityParams) (*UpdateActivityResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out UpdateActivityResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateActivityStreamsParams struct {
	ID   string
	Body UpdateActivityStreamsRequestBody
}

type UpdateActivityStreamsResult = UpdateStreamsResult

func (c *Client) UpdateActivityStreams(ctx context.Context, params UpdateActivityStreamsParams) (*UpdateActivityStreamsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out UpdateActivityStreamsResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}/streams", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateAthleteParams struct {
	ID   string
	Body AthleteUpdateDTO
}

type UpdateAthleteResult = Athlete

func (c *Client) UpdateAthlete(ctx context.Context, params UpdateAthleteParams) (*UpdateAthleteResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateAthleteResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateAthletePlanParams struct {
	ID   string
	Body AthleteTrainingPlanUpdate
}

type UpdateAthletePlanResult = AthleteTrainingPlan

func (c *Client) UpdateAthletePlan(ctx context.Context, params UpdateAthletePlanParams) (*UpdateAthletePlanResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateAthletePlanResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/training-plan", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateAthletePlansParams struct {
	Body UpdateAthletePlansRequestBody
}

type UpdateAthletePlansResult = UpdateAthletePlansResultBody

func (c *Client) UpdateAthletePlans(ctx context.Context, params UpdateAthletePlansParams) (*UpdateAthletePlansResult, error) {
	pathParams := map[string]string{}
	query := url.Values{}
	var out UpdateAthletePlansResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete-plans", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateAthleteRouteParams struct {
	ID      string
	RouteID int64
	Body    AthleteRoute
}

type UpdateAthleteRouteResult = AthleteRoute

func (c *Client) UpdateAthleteRoute(ctx context.Context, params UpdateAthleteRouteParams) (*UpdateAthleteRouteResult, error) {
	pathParams := map[string]string{
		"id":       c.athleteIDOr(params.ID),
		"route_id": fmt.Sprint(params.RouteID),
	}
	query := url.Values{}
	var out UpdateAthleteRouteResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/routes/{route_id}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateCustomItemParams struct {
	ID     string
	ItemID int32
	Body   CustomItem
}

type UpdateCustomItemResult = CustomItem

func (c *Client) UpdateCustomItem(ctx context.Context, params UpdateCustomItemParams) (*UpdateCustomItemResult, error) {
	pathParams := map[string]string{
		"id":     c.athleteIDOr(params.ID),
		"itemId": fmt.Sprint(params.ItemID),
	}
	query := url.Values{}
	var out UpdateCustomItemResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/custom-item/{itemId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateCustomItemImageParams struct {
	ID     string
	ItemID int32
	Body   *UpdateCustomItemImageRequestBody
}

type UpdateCustomItemImageResult = CustomItem

func (c *Client) UpdateCustomItemImage(ctx context.Context, params UpdateCustomItemImageParams) (*UpdateCustomItemImageResult, error) {
	pathParams := map[string]string{
		"id":     c.athleteIDOr(params.ID),
		"itemId": fmt.Sprint(params.ItemID),
	}
	query := url.Values{}
	var out UpdateCustomItemImageResult
	if err := c.doMultipart(ctx, "POST", "/api/v1/athlete/{id}/custom-item/{itemId}/image", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateCustomItemIndexesParams struct {
	ID   string
	Body UpdateCustomItemIndexesRequestBody
}

type UpdateCustomItemIndexesResult = struct{}

func (c *Client) UpdateCustomItemIndexes(ctx context.Context, params UpdateCustomItemIndexesParams) (*UpdateCustomItemIndexesResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateCustomItemIndexesResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/custom-item-indexes", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateEventParams struct {
	EventID int32
	ID      string
	Body    EventEx
}

type UpdateEventResult = Event

func (c *Client) UpdateEvent(ctx context.Context, params UpdateEventParams) (*UpdateEventResult, error) {
	pathParams := map[string]string{
		"eventId": fmt.Sprint(params.EventID),
		"id":      c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateEventResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/events/{eventId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateEventsParams struct {
	ID     string
	Newest string
	Oldest string
	Body   Event
}

type UpdateEventsResult = UpdateEventsResultBody

func (c *Client) UpdateEvents(ctx context.Context, params UpdateEventsParams) (*UpdateEventsResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	var out UpdateEventsResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/events", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateFolderParams struct {
	FolderID int32
	ID       string
	Body     Folder
}

type UpdateFolderResult = Folder

func (c *Client) UpdateFolder(ctx context.Context, params UpdateFolderParams) (*UpdateFolderResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateFolderResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/folders/{folderId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateFolderSharedWithParams struct {
	FolderID int32
	ID       string
	Body     UpdateFolderSharedWithRequestBody
}

type UpdateFolderSharedWithResult = UpdateFolderSharedWithResultBody

func (c *Client) UpdateFolderSharedWith(ctx context.Context, params UpdateFolderSharedWithParams) (*UpdateFolderSharedWithResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateFolderSharedWithResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/folders/{folderId}/shared-with", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateGearParams struct {
	GearID string
	ID     string
	Body   Gear
}

type UpdateGearResult = Gear

func (c *Client) UpdateGear(ctx context.Context, params UpdateGearParams) (*UpdateGearResult, error) {
	pathParams := map[string]string{
		"gearId": fmt.Sprint(params.GearID),
		"id":     c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateGearResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/gear/{gearId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateIntervalParams struct {
	ID         string
	IntervalID int32
	Body       Interval
}

type UpdateIntervalResult = IntervalsDTO

func (c *Client) UpdateInterval(ctx context.Context, params UpdateIntervalParams) (*UpdateIntervalResult, error) {
	pathParams := map[string]string{
		"id":         fmt.Sprint(params.ID),
		"intervalId": fmt.Sprint(params.IntervalID),
	}
	query := url.Values{}
	var out UpdateIntervalResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}/intervals/{intervalId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateIntervalsParams struct {
	ID   string
	All  *bool
	Body UpdateIntervalsRequestBody
}

type UpdateIntervalsResult = IntervalsDTO

func (c *Client) UpdateIntervals(ctx context.Context, params UpdateIntervalsParams) (*UpdateIntervalsResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	if params.All != nil {
		query.Set("all", fmt.Sprint(*params.All))
	}
	var out UpdateIntervalsResult
	if err := c.do(ctx, "PUT", "/api/v1/activity/{id}/intervals", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateLastSeenMessageIDParams struct {
	ID    int32
	MsgID int64
}

type UpdateLastSeenMessageIDResult = UpdateLastSeenMessageIDResultBody

func (c *Client) UpdateLastSeenMessageID(ctx context.Context, params UpdateLastSeenMessageIDParams) (*UpdateLastSeenMessageIDResult, error) {
	pathParams := map[string]string{
		"id":    fmt.Sprint(params.ID),
		"msgId": fmt.Sprint(params.MsgID),
	}
	query := url.Values{}
	var out UpdateLastSeenMessageIDResult
	if err := c.do(ctx, "PUT", "/api/v1/chats/{id}/messages/{msgId}/seen", pathParams, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdatePlanWorkoutsParams struct {
	FolderID int32
	ID       string
	Newest   int32
	Oldest   int32
	Body     Workout
}

type UpdatePlanWorkoutsResult = UpdatePlanWorkoutsResultBody

func (c *Client) UpdatePlanWorkouts(ctx context.Context, params UpdatePlanWorkoutsParams) (*UpdatePlanWorkoutsResult, error) {
	pathParams := map[string]string{
		"folderId": fmt.Sprint(params.FolderID),
		"id":       c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	query.Set("newest", fmt.Sprint(params.Newest))
	query.Set("oldest", fmt.Sprint(params.Oldest))
	var out UpdatePlanWorkoutsResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/folders/{folderId}/workouts", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateReminderParams struct {
	GearID     string
	ID         string
	ReminderID int32
	Reset      bool
	SnoozeDays int32
	Body       GearReminder
}

type UpdateReminderResult = Gear

func (c *Client) UpdateReminder(ctx context.Context, params UpdateReminderParams) (*UpdateReminderResult, error) {
	pathParams := map[string]string{
		"gearId":     fmt.Sprint(params.GearID),
		"id":         c.athleteIDOr(params.ID),
		"reminderId": fmt.Sprint(params.ReminderID),
	}
	query := url.Values{}
	query.Set("reset", fmt.Sprint(params.Reset))
	query.Set("snoozeDays", fmt.Sprint(params.SnoozeDays))
	var out UpdateReminderResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/gear/{gearId}/reminder/{reminderId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateSettingsParams struct {
	AthleteID     string
	ID            string
	RecalcHRZones bool
	Body          SportSettings
}

type UpdateSettingsResult = SportSettings

func (c *Client) UpdateSettings(ctx context.Context, params UpdateSettingsParams) (*UpdateSettingsResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
		"id":        fmt.Sprint(params.ID),
	}
	query := url.Values{}
	query.Set("recalcHrZones", fmt.Sprint(params.RecalcHRZones))
	var out UpdateSettingsResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{athleteId}/sport-settings/{id}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateSettingsMultiParams struct {
	AthleteID     string
	RecalcHRZones bool
	Body          UpdateSettingsMultiRequestBody
}

type UpdateSettingsMultiResult = UpdateSettingsMultiResultBody

func (c *Client) UpdateSettingsMulti(ctx context.Context, params UpdateSettingsMultiParams) (*UpdateSettingsMultiResult, error) {
	pathParams := map[string]string{
		"athleteId": fmt.Sprint(params.AthleteID),
	}
	query := url.Values{}
	query.Set("recalcHrZones", fmt.Sprint(params.RecalcHRZones))
	var out UpdateSettingsMultiResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{athleteId}/sport-settings", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateSharedEventParams struct {
	ID   int32
	Body SharedEvent
}

type UpdateSharedEventResult = SharedEvent

func (c *Client) UpdateSharedEvent(ctx context.Context, params UpdateSharedEventParams) (*UpdateSharedEventResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out UpdateSharedEventResult
	if err := c.do(ctx, "PUT", "/api/v1/shared-event/{id}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateWeatherConfigParams struct {
	ID   string
	Body WeatherConfig
}

type UpdateWeatherConfigResult = WeatherConfig

func (c *Client) UpdateWeatherConfig(ctx context.Context, params UpdateWeatherConfigParams) (*UpdateWeatherConfigResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateWeatherConfigResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/weather-config", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateWellnessParams struct {
	Date string
	ID   string
	Body Wellness
}

type UpdateWellnessResult = Wellness

func (c *Client) UpdateWellness(ctx context.Context, params UpdateWellnessParams) (*UpdateWellnessResult, error) {
	pathParams := map[string]string{
		"date": fmt.Sprint(params.Date),
		"id":   c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateWellnessResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/wellness/{date}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateWellness1Params struct {
	ID   string
	Body Wellness
}

type UpdateWellness1Result = Wellness

func (c *Client) UpdateWellness1(ctx context.Context, params UpdateWellness1Params) (*UpdateWellness1Result, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateWellness1Result
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/wellness", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateWellnessBulkParams struct {
	ID   string
	Body UpdateWellnessBulkRequestBody
}

type UpdateWellnessBulkResult = struct{}

func (c *Client) UpdateWellnessBulk(ctx context.Context, params UpdateWellnessBulkParams) (*UpdateWellnessBulkResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	var out UpdateWellnessBulkResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/wellness-bulk", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UpdateWorkoutParams struct {
	ID        string
	WorkoutID int32
	Body      WorkoutEx
}

type UpdateWorkoutResult = Workout

func (c *Client) UpdateWorkout(ctx context.Context, params UpdateWorkoutParams) (*UpdateWorkoutResult, error) {
	pathParams := map[string]string{
		"id":        c.athleteIDOr(params.ID),
		"workoutId": fmt.Sprint(params.WorkoutID),
	}
	query := url.Values{}
	var out UpdateWorkoutResult
	if err := c.do(ctx, "PUT", "/api/v1/athlete/{id}/workouts/{workoutId}", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UploadActivityParams struct {
	ID            string
	Description   *string
	DeviceName    *string
	ExternalID    *string
	Name          *string
	PairedEventID *int32
	Body          *UploadActivityRequestBody
}

type UploadActivityResult = UploadResponse

func (c *Client) UploadActivity(ctx context.Context, params UploadActivityParams) (*UploadActivityResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.Description != nil {
		query.Set("description", fmt.Sprint(*params.Description))
	}
	if params.DeviceName != nil {
		query.Set("device_name", fmt.Sprint(*params.DeviceName))
	}
	if params.ExternalID != nil {
		query.Set("external_id", fmt.Sprint(*params.ExternalID))
	}
	if params.Name != nil {
		query.Set("name", fmt.Sprint(*params.Name))
	}
	if params.PairedEventID != nil {
		query.Set("paired_event_id", fmt.Sprint(*params.PairedEventID))
	}
	var out UploadActivityResult
	if err := c.doMultipart(ctx, "POST", "/api/v1/athlete/{id}/activities", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UploadActivityStreamsCsvParams struct {
	ID   string
	Body *UploadActivityStreamsCsvRequestBody
}

type UploadActivityStreamsCsvResult = UpdateStreamsResult

func (c *Client) UploadActivityStreamsCsv(ctx context.Context, params UploadActivityStreamsCsvParams) (*UploadActivityStreamsCsvResult, error) {
	pathParams := map[string]string{
		"id": fmt.Sprint(params.ID),
	}
	query := url.Values{}
	var out UploadActivityStreamsCsvResult
	if err := c.doMultipart(ctx, "PUT", "/api/v1/activity/{id}/streams.csv", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

type UploadWellnessParams struct {
	ID                  string
	IgnoreMissingFields *bool
	Body                *UploadWellnessRequestBody
}

type UploadWellnessResult = UploadWellnessResultBody

func (c *Client) UploadWellness(ctx context.Context, params UploadWellnessParams) (*UploadWellnessResult, error) {
	pathParams := map[string]string{
		"id": c.athleteIDOr(params.ID),
	}
	query := url.Values{}
	if params.IgnoreMissingFields != nil {
		query.Set("ignoreMissingFields", fmt.Sprint(*params.IgnoreMissingFields))
	}
	var out UploadWellnessResult
	if err := c.doMultipart(ctx, "POST", "/api/v1/athlete/{id}/wellness", pathParams, query, params.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
